#!/usr/bin/env python3
"""Plot VDP HJB activation families.

If a full variant-level results.tsv is present, consolidate variants by family.
Otherwise, use analysis/family_representatives.tsv generated by
analyze_softplus.py.
"""
from __future__ import annotations

import csv
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
FULL_TSV = ROOT / "results.tsv"
FAMILY_TSV = ROOT / "analysis" / "family_representatives.tsv"
FLOOR = 0.30


def family_name(name: str) -> str:
    if name.startswith("softplus_b"):
        return "Softplus"
    if name.startswith("gelu_b"):
        return "GELU"
    if name.startswith("mish_b"):
        return "Mish"
    if name.startswith("smoothy_relu"):
        return "SmoothReLU"
    if name.startswith("sp2_") or name.startswith("softplus_squared"):
        return "Softplus^2"
    if name.startswith("qr_"):
        return "Quadratic residual"
    if name == "relu":
        return "ReLU"
    return name.replace("_", " ")


def variant(name: str) -> str:
    match = re.search(r"_b([0-9_]+)$", name)
    if match:
        return "beta=" + match.group(1).replace("_", ".")
    match = re.search(r"_w(.+)$", name)
    if match:
        return "w=" + match.group(1).replace("_", ".")
    return "baseline"


def load_rows() -> list[dict]:
    if FULL_TSV.exists():
        with FULL_TSV.open() as file:
            variants = list(csv.DictReader(file, delimiter="\t"))
        reps: dict[str, dict] = {}
        for row in variants:
            row = dict(row)
            row["family"] = family_name(row["activation"])
            row["variant"] = variant(row["activation"])
            row["mean_score"] = float(row["mean_score"])
            row["std_score"] = float(row["std_score"])
            row["mean_h1"] = float(row["mean_h1"])
            row["mean_neurons"] = float(row["mean_neurons"])
            family = row["family"]
            if family not in reps or row["mean_score"] < reps[family]["mean_score"]:
                reps[family] = row
        return list(reps.values())

    if not FAMILY_TSV.exists():
        raise SystemExit(
            f"missing {FULL_TSV} and {FAMILY_TSV}; run analyze_softplus.py first"
        )
    with FAMILY_TSV.open() as file:
        rows = list(csv.DictReader(file))
    for row in rows:
        row["mean_score"] = float(row["mean_score"])
        row["std_score"] = float(row["std_score"])
        row["mean_h1"] = float(row["mean_h1"])
        row["mean_neurons"] = float(row["mean_neurons"])
    return rows


rows = load_rows()
points = sorted(rows, key=lambda row: row["mean_h1"])
frontier = []
best_h1 = float("inf")
for row in sorted(rows, key=lambda item: item["mean_neurons"]):
    if row["mean_h1"] < best_h1:
        frontier.append(row)
        best_h1 = row["mean_h1"]

fig, axes = plt.subplots(1, 2, figsize=(15, 6), gridspec_kw={"width_ratios": [1.1, 1.2]})

ax = axes[0]
scatter = ax.scatter(
    [row["mean_neurons"] for row in points],
    [row["mean_h1"] for row in points],
    s=85,
    c=[row["mean_score"] for row in points],
    cmap="viridis_r",
    edgecolors="black",
    zorder=3,
)
frontier_x = [row["mean_neurons"] for row in frontier]
frontier_y = [row["mean_h1"] for row in frontier]
ax.step(
    frontier_x,
    frontier_y,
    where="post",
    color="black",
    linestyle="--",
    linewidth=1.3,
    label="family Pareto frontier",
    zorder=2,
)
ax.scatter(frontier_x, frontier_y, c="black", s=28, zorder=4)
for row in points:
    ax.annotate(
        row["family"],
        (row["mean_neurons"], row["mean_h1"]),
        xytext=(5, 4),
        textcoords="offset points",
        fontsize=8,
    )
ax.axhline(FLOOR, color="tab:purple", linestyle=":", linewidth=1, alpha=0.5)
ns = np.linspace(5, max(row["mean_neurons"] for row in rows) + 10, 220)
for score in [6, 10, 16, 24]:
    h1 = score / ns
    mask = (h1 >= 0.10) & (h1 <= 0.31)
    if mask.any():
        ax.plot(ns[mask], h1[mask], "b:", lw=0.7, alpha=0.35)
        idx = np.where(mask)[0][len(np.where(mask)[0]) // 2]
        ax.text(ns[idx], h1[idx], f"s={score}", fontsize=7, color="blue", alpha=0.6)
ax.set_xlabel("mean neurons")
ax.set_ylabel("mean H1")
ax.set_title("Activation families: Pareto frontier")
ax.grid(True, alpha=0.3)
ax.legend(loc="upper right", fontsize=8)
fig.colorbar(scatter, ax=ax, label="score = H1 x neurons")

ax2 = axes[1]
top = sorted(rows, key=lambda row: row["mean_score"])
labels = [f"{row['family']} ({row['variant']})" for row in top]
ypos = list(range(len(top)))
ax2.barh(
    ypos,
    [row["mean_score"] for row in top],
    xerr=[row["std_score"] for row in top],
    color="lightblue",
    edgecolor="black",
    capsize=3,
)
ax2.set_yticks(ypos)
ax2.set_yticklabels(labels, fontsize=9)
ax2.invert_yaxis()
ax2.set_xlabel("score = H1 x neurons")
ax2.set_title("Consolidated activation families")
ax2.grid(True, axis="x", alpha=0.3)

plt.tight_layout()
out = ROOT / "pareto.png"
plt.savefig(out, dpi=130, bbox_inches="tight")
print(f"saved {out}")
plt.close()
